### PR TITLE
Replace arcsin & seterr by their Numpy equivalent

### PR DESCRIPTION
**Pull request by smazoyer**
These functions will be removed in SciPy 2.0.0. Deprecation warnings start to appear in Scipy 1.4.1

### CODE REVIEW

**Comment by smazoyer** [comment]
Thanks a lot for your package. 
I use it recently with a recent version of Scipy (1.4.1) and I noticed deprecation warnings for scipy functions. I followed the recommendations proposed by Scipy and use the equivalent function in Numpy. 
The tests seems to be OK and it is working OK for my usage. 
I don't know if these changes are compatible with older versions of Numpy.

**Comment by sbyrnes321** [comment]
Awesome!!! If you have a chance, can you also add a commit that updates the comment:

    # Important that the arcsin here is scipy.arcsin, not numpy.arcsin! (They
    # give different results e.g. for arcsin(2).)

to something like

    # Important that the arcsin here is numpy.lib.scimath.arcsin, not
    # numpy.arcsin! (They give different results e.g. for arcsin(2).)

Or otherwise I can do it.

Thanks!!

**Comment by sbyrnes321** [comment]
This is incorporated into version 0.1.8, now on PyPI. Thanks again!

**Comment by smazoyer** [comment]
Thanks to you.

**Pull request merged**
