### PR TITLE
Fixes issue #12

### PR DESCRIPTION
**Pull request by dkuersch**

### CODE REVIEW

**Comment by sbyrnes321** [comment]
j is intended to be a single-element array, right? If so, would it work to do `j = inc_data['stack_from_all'][layer].item()` instead? Just thinking that might be clearer. Running any() on an array that we fully expect to have only one element seems like it would be confusing. Sorry in advance if I’m confused about what’s going on.

**Comment by dkuersch** [comment]
As far as I can see, j is just a single element if the layer is incoherent, right? If the layer is coherent it is a two element list -> see eg. info comment in def inc_group_layers(n_list, d_list, c_list) (line 757)

At least for my minimal working example shown below j is not a single element list but has len(j) = 2:  j = [0,1]

```
import tmm
import numpy as np

pol = "s"
lam_vac = 460e-9
ang_inc = 0

air = {"d": np.inf, "scatter_type": "i", "n": 1.00028018}
glass = {"d": 1e-3, "scatter_type": "i", "n": 1.4648}
ito = {"d": 120e-9, "scatter_type": "c", "n": 1.9932 + 0.0039253j}


material_stack = [air, glass, ito, air]

n_stack = [mat["n"] for mat in material_stack]
thick_stack = [mat["d"] for mat in material_stack]
c_stack = [mat["scatter_type"] for mat in material_stack]


inc_res = tmm.inc_tmm(
    pol=pol,
    n_list=n_stack,
    d_list=thick_stack,
    c_list=c_stack,
    th_0=ang_inc,
    lam_vac=lam_vac,
)


fns = []
z_tot = [[0]]
n_z = 50
for i in range(len(n_stack)):
    if c_stack[i] != "i":

        z = np.linspace(0, thick_stack[i], n_z)
        fn = tmm.inc_find_absorp_analytic_fn(
            layer=i, inc_data=inc_res
        ).run(z)

        fns.append(np.real(fn))
        z_tot.append(z_tot[-1][-1] + z)

import matplotlib.pyplot as plt
a_z = np.concatenate(fns)
z_tot = np.concatenate(z_tot[1:])
plt.plot(z_tot, a_z)
plt.show()
```
If you would use .item() you will get an AttributeError: 

> Traceback (most recent call last):
>   File "c:\Git\...\TTM\try_absorp_analytic_fn_inc_issue12.py", line 39, in <module>
>     fn = tmm.inc_find_absorp_analytic_fn(
>   File "c:\Git\...\TTM\venv\lib\site-packages\tmm\tmm_core.py", line 1208, in inc_find_absorp_analytic_fn
>     j = inc_data["stack_from_all"][layer].item()
> AttributeError: 'list' object has no attribute 'item'

I didn't know if there can be any case in which j can have a nan-element. Thats why I suggested the np.any().

Cheers,
Dorian

**Comment by sbyrnes321** [comment]
Ah, makes sense, sorry. Did you test the updated code with both incoherent and coherent cases? If so, I’ll merge. (I can’t easily test it myself right now.)

**Comment by dkuersch** [comment]
What I tested was:

- `tmm.inc_find_absorp_analytic_fn()` gives the same result as `tmm.absorp_analytic_fn()` for a fully coherent layered system `material_stack = [air, mat1, mat2, mat3, air]`. The results are the same.
```
import tmm

import numpy as np


pol = "s"
lam_vac = 460e-9
ang_inc = 0

air = {"d": np.inf, "scatter_type": "i", "n": 1.00028018}
mat1 = {"d": 200e-9, "scatter_type": "c", "n": 1.9 + 0.3j}
mat2 = {"d": 100e-9, "scatter_type": "c", "n": 2.5 + 0.1j}
mat3 = {"d": 50e-9, "scatter_type": "c", "n": 3.6 + 0.4j}
subst = {"d": 1e-3, "scatter_type": "i", "n": 1.4648}


material_stack = [air, mat1, mat2, mat3, air]
material_stack_coh = [air, mat1, mat2, mat3, air]

n_stack = [mat["n"] for mat in material_stack]
thick_stack = [mat["d"] for mat in material_stack]
c_stack = [mat["scatter_type"] for mat in material_stack]

n_stack_coh = [mat["n"] for mat in material_stack_coh]
thick_stack_coh = [mat["d"] for mat in material_stack_coh]


inc_res = tmm.inc_tmm(
    pol=pol,
    n_list=n_stack,
    d_list=thick_stack,
    c_list=c_stack,
    th_0=ang_inc,
    lam_vac=lam_vac,
)

coh_res = tmm.coh_tmm(
    pol=pol,
    n_list=n_stack_coh,
    d_list=thick_stack_coh,
    th_0=ang_inc,
    lam_vac=lam_vac,
)


fns = []
z_tot = [[0]]
n_z = 50
for i in range(len(n_stack)):
    if c_stack[i] != "i":

        z = np.linspace(0, thick_stack[i], n_z)
        fn = tmm.inc_find_absorp_analytic_fn(
            layer=i, inc_data=inc_res
        ).run(z)

        fns.append(np.real(fn))
        z_tot.append(z_tot[-1][-1] + z)

fns_coh = []
z_tot_coh = [[0]]
for i in range(len(n_stack_coh)):
    if thick_stack_coh[i] is not np.inf:

        z = np.linspace(0, thick_stack_coh[i], n_z)

        fn = tmm.absorp_analytic_fn().fill_in(coh_res, i).run(z)

        fns_coh.append(np.real(fn))
        z_tot_coh.append(z_tot_coh[-1][-1] + z)

import matplotlib.pyplot as plt

a_z = np.concatenate(fns)
z_tot = np.concatenate(z_tot[1:])

a_z_coh = np.concatenate(fns_coh)
z_tot_coh = np.concatenate(z_tot_coh[1:])

print(np.nonzero(a_z - a_z_coh))

plt.subplot(121)
plt.plot(z_tot, a_z, label="inc")
plt.plot(z_tot_coh, a_z_coh, label="coh", ls=":", lw=5)
plt.xlabel("z [m]")
plt.ylabel(r"$a(z)$ [1/m]")
plt.xlim([0, 300e-9])
plt.legend()
plt.subplot(122)
plt.plot(z_tot, a_z - a_z_coh)
plt.xlabel("z [m]")
plt.ylabel(r"$a_{inc}(z)-a_{coh}(z)$ [1/m]")
plt.tight_layout()
plt.show()
```

- If I compare an incoherent substrate(using `tmm_inc` )and a coherent substrate(using  `tmm.coh` respectively) for the `material_stack = [air, mat1, mat2, mat3, subst, air]` of course the results differ since the E-field is treated differently in the methods for the coherent and incoherent case. Therefore these cases are not really comparable.

If you have any idea what I should further test, please let me know!

Cheers

**Pull request merged**
